dist: focal
os: linux
jobs:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=lint
      dist: focal
    - python: "3.6"
      env: TOXENV=pylint
      dist: focal
    - python: "3.6"
      env: TOXENV=typing
      dist: focal
    - python: "3.6"
      env: TOXENV=py36
      dist: focal
    - python: "3.7"
      env: TOXENV=py37
      dist: focal
    - python: "3.8"
      env: TOXENV=py38
      dist: focal
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: focal
  allow_failures:
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: focal

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script: travis_wait 30 tox
services:
  - docker
